
let CountryDictShortcuts = new Map<string, string>();
CountryDictShortcuts.set('Ecuador', 'ECU')
CountryDictShortcuts.set('Netherlands', 'NL')
CountryDictShortcuts.set('Qatar', 'QAT')
CountryDictShortcuts.set('Senegal', 'SEN')
CountryDictShortcuts.set('Poland', 'POL')
CountryDictShortcuts.set('England', 'ENG')
CountryDictShortcuts.set('Wales', 'WAL')
CountryDictShortcuts.set('Argentina', 'ARG')
CountryDictShortcuts.set('Mexico', 'MEX')
CountryDictShortcuts.set('Saudi Arabia', 'SA')
CountryDictShortcuts.set('Tunisia', 'TUN')
CountryDictShortcuts.set('Iran', 'IR')
CountryDictShortcuts.set('France', 'FRA')
CountryDictShortcuts.set('Australia', 'AUS')
CountryDictShortcuts.set('Germany', 'GER')
CountryDictShortcuts.set('Japan', 'JAP')
CountryDictShortcuts.set('Spain', 'ES')
CountryDictShortcuts.set('Costa Rica', 'CR')
CountryDictShortcuts.set('Morocco', 'MOR')
CountryDictShortcuts.set('Croatia', 'CRO')
CountryDictShortcuts.set('Belgium', 'BEL')
CountryDictShortcuts.set('Canada', 'CAN')
CountryDictShortcuts.set('Switzerland', 'SWI')
CountryDictShortcuts.set('Brazil', 'BRA')
CountryDictShortcuts.set('Serbia', 'SER')
CountryDictShortcuts.set('Cameroon', 'CAM')
CountryDictShortcuts.set('Uruguay', 'URU')
CountryDictShortcuts.set('Korea Republic', 'KOR')
CountryDictShortcuts.set('Portugal', 'POR')
CountryDictShortcuts.set('Ghana', 'GHA')
CountryDictShortcuts.set('USA', 'USA')
CountryDictShortcuts.set('Greece', 'GRE')
CountryDictShortcuts.set('Denmark', 'DEN')

export default CountryDictShortcuts;